# Project Euler - Problem 12
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?
#
# Darren Brain
# darren.brain@gmail.com
# 3/1/2016
from math import sqrt
num = 1
triangle = 1
answer_found = False

while answer_found == False:
    num += 1
    triangle += num
    factor_count = 0
    for check_factors in range(1,int(sqrt(triangle)+1)):
        if triangle % check_factors == 0:
            factor_count += 2
            if factor_count > 500:
                print(triangle)
                answer_found = True
    print(factor_count, ftriangle)