# Project Euler - Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

total = 0
first_value = 1
second_value = 2


while first_value < 4000001:
    if first_value % 2 == 0:
        total += first_value
    hold_value = second_value
    second_value += first_value
    first_value = hold_value

print(total)
